# Importing Libraries

In [1]:

import numpy as np
import pandas as pd

# Loading All The Csv Files

In [2]:
#loading all the datasets
customers_raw = pd.read_csv('data/CUSTOMERS.csv')
geo_location_raw = pd.read_csv('data/GEO_LOCATION.csv')
orders_itmes_raw = pd.read_csv('data/ORDER_ITEMS.csv')
orders_payments_raw = pd.read_csv('data/ORDER_PAYMENTS.csv')
order_review_ratings_raw = pd.read_csv('data/ORDER_REVIEW_RATINGS.csv')
orders_raw = pd.read_csv('data/ORDERS.csv')
products_raw = pd.read_csv('data/PRODUCTS.csv')
sellers_raw = pd.read_csv('data/SELLERS.csv')

In [3]:
tables = [customers_raw , geo_location_raw ,orders_itmes_raw,orders_payments_raw,order_review_ratings_raw,orders_raw,products_raw,sellers_raw]

In [4]:
#making copy of each data set so orginal raw data is safe
customers=customers_raw.copy()
geo_location=geo_location_raw.copy()
orders_itmes=orders_itmes_raw.copy()
orders_payments=orders_payments_raw.copy()
order_review_ratings=order_review_ratings_raw.copy()
orders=orders_raw.copy()
products=products_raw.copy()
sellers=sellers_raw.copy()

# customers_raw inspecting and missing value handling , delete duplicates and filtering

In [5]:
customers_raw.head(1)

,customer_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,14409,Adilabad,Andhra Pradesh

In [6]:
geo_location_raw.head(1)

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1037,-23.545621,-46.639292,Akkarampalle,Andhra Pradesh

In [7]:
orders_itmes_raw.head(1)

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,9/19/2017 9:45,58.9,13.29

In [8]:
orders_payments_raw.head(1)

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33

In [9]:
order_review_ratings_raw.head(1)

,review_id,order_id,review_score,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,1/18/2018 0:00,1/18/2018 21:46

In [10]:
orders_raw.head(1)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,10/2/2017 10:56,10/2/2017 11:07,10/4/2017 19:55,10/10/2017 21:25,10/18/2017 0:00

In [11]:
products_raw.head(1)

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,Perfumery,40.0,287.0,1.0,225.0,16.0,10.0,14.0

In [12]:
sellers_raw.head(1)

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,Alwal,Andhra Pradesh

In [13]:

for tbl in tables:
    print(tbl.info())
    print('shape =',tbl.shape)
    print('null count\n',tbl.isna().sum())
    print('duplicates = ',tbl.duplicated().sum())
    print('\n\n\n')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 4 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  object
 1   customer_zip_code_prefix  99441 non-null  int64
 2   customer_city             99441 non-null  object
 3   customer_state            99441 non-null  object
dtypes: int64(1), object(3)
memory usage: 3.0+ MB
None
shape = (99441, 4)
null count
 customer_id                 0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64
duplicates =  0




<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19015 entries, 0 to 19014
Data columns (total 5 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   geolocation_zip_code_prefix  19015 non-null  int64
 1   geolocation_lat              19015 non-null  float64
 2   geolocation_lng              19015 non-null  float64
 3   geolocation_city             19015 non-null  object
 4   geolocation_state            19015 non-null  object
dtypes: float64(2), int64(1), object(2)
memory usage: 742.9+ KB
None
shape = (19015, 5)
null count
 geolocation_zip_code_prefix    0
geolocation_lat                0
geolocation_lng                0
geolocation_city               0
geolocation_state              0
dtype: int64
duplicates =  0




<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  object
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  object
 3   seller_id            112650 non-null  object
 4   shipping_limit_date  112650 non-null  object
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: float64(2), int64(1), object(4)
memory usage: 6.0+ MB
None
shape = (112650, 7)
null count
 order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64
duplicates =  0




<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   order_id              103886 non-null  object
 1   payment_sequential    103886 non-null  int64
 2   payment_type          103886 non-null  object
 3   payment_installments  103886 non-null  int64
 4   payment_value         103886 non-null  float64
dtypes: float64(1), int64(2), object(2)
memory usage: 4.0+ MB
None
shape = (103886, 5)
null count
 order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64
duplicates =  0




<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 5 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   review_id                100000 non-null  object
 1   order_id                 100000 non-null  object
 2   review_score             100000 non-null  int64
 3   review_creation_date     100000 non-null  object
 4   review_answer_timestamp  100000 non-null  object
dtypes: int64(1), object(4)
memory usage: 3.8+ MB
None
shape = (100000, 5)
null count
 review_id                  0
order_id                   0
review_score               0
review_creation_date       0
review_answer_timestamp    0
dtype: int64
duplicates =  0




<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  object
 4   order_approved_at              99281 non-null  object
 5   order_delivered_carrier_date   97658 non-null  object
 6   order_delivered_customer_date  96476 non-null  object
 7   order_estimated_delivery_date  99441 non-null  object
dtypes: object(8)
memory usage: 6.1+ MB
None
shape = (99441, 8)
null count
 order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64
duplicates =  0




<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  32951 non-null  object
 1   product_category_name       32328 non-null  object
 2   product_name_lenght         32341 non-null  float64
 3   product_description_lenght  32341 non-null  float64
 4   product_photos_qty          32341 non-null  float64
 5   product_weight_g            32949 non-null  float64
 6   product_length_cm           32949 non-null  float64
 7   product_height_cm           32949 non-null  float64
 8   product_width_cm            32949 non-null  float64
dtypes: float64(7), object(2)
memory usage: 2.3+ MB
None
shape = (32951, 9)
null count
 product_id                      0
product_category_name         623
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64
duplicates =  0




<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3095 entries, 0 to 3094
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   seller_id               3095 non-null   object
 1   seller_zip_code_prefix  3095 non-null   int64
 2   seller_city             3038 non-null   object
 3   seller_state            3038 non-null   object
dtypes: int64(1), object(3)
memory usage: 96.8+ KB
None
shape = (3095, 4)
null count
 seller_id                  0
seller_zip_code_prefix     0
seller_city               57
seller_state              57
dtype: int64
duplicates =  0

##  converting data types
### tables need converrsion - orders_itmes , order_review_ratings ,orders

In [14]:
#orders_items - shipping_limit_date
orders_itmes['shipping_limit_date'] = pd.to_datetime(orders_itmes['shipping_limit_date'] , errors='coerce')

In [15]:
orders_itmes.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:00,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:00,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:00,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:00,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:00,199.90,18.14

In [16]:
#order_review_ratings - review_creation_date , review_answer_timestamp

order_review_ratings['review_creation_date']= pd.to_datetime(order_review_ratings['review_creation_date'], errors='coerce')
order_review_ratings['review_answer_timestamp']= pd.to_datetime(order_review_ratings['review_answer_timestamp'], errors='coerce')

In [17]:
order_review_ratings.head()

,review_id,order_id,review_score,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,2018-01-18,2018-01-18 21:46:00
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,2018-03-10,2018-03-11 03:05:00
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,2018-02-17,2018-02-18 14:36:00
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,2017-04-21,2017-04-21 22:02:00
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,2018-03-01,2018-03-02 10:26:00

In [18]:
#orders - order_estimated_delivery_date , order_delivered_customer_date , order_delivered_carrier, 
# order_approved_at, order_purchase_timestamp, 
orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,10/2/2017 10:56,10/2/2017 11:07,10/4/2017 19:55,10/10/2017 21:25,10/18/2017 0:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,7/24/2018 20:41,7/26/2018 3:24,7/26/2018 14:31,8/7/2018 15:27,8/13/2018 0:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,8/8/2018 8:38,8/8/2018 8:55,8/8/2018 13:50,8/17/2018 18:06,9/4/2018 0:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,11/18/2017 19:28,11/18/2017 19:45,11/22/2017 13:39,12/2/2017 0:28,12/15/2017 0:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2/13/2018 21:18,2/13/2018 22:20,2/14/2018 19:46,2/16/2018 18:17,2/26/2018 0:00

In [19]:
date_concersion_cols = ['order_estimated_delivery_date' , 'order_delivered_customer_date' , 'order_delivered_carrier_date', 'order_approved_at', 'order_purchase_timestamp' ]

for c in date_concersion_cols:
    orders[c]= pd.to_datetime(orders[c], errors='coerce')

orders.head()

orders['order_purchase_timestamp'] = pd.to_datetime(
    orders['order_purchase_timestamp'],
    errors='coerce'
)

## null value handling
### columns containg null = orders_raw, products_raw, sellers_raw

In [20]:
#orders
print(orders.isna().sum())
print(orders.shape)


#the dates nan will be keep as it as it can be the orders which is cancel never went for dilivery 
#or didnt recived to customres so it will be keep as nan

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64
(99441, 8)

In [21]:
#products
print('Before')
print(products.shape)
print(products.isna().sum())
#product_category_name         623 - replace with unknown catagoery
#product_name_lenght           610 - impute with median
#product_description_lenght    610 - impute with median
#product_photos_qty            610 - impute with median
#product_weight_g                2 - impute with median
#product_length_cm               2 - impute with median
#product_height_cm               2 - impute with median
#product_width_cm                2 - impute with median
products['product_category_name'] = (products['product_category_name'].fillna('unknown'))

missing_cols = [
    'product_name_lenght',
    'product_description_lenght',
    'product_photos_qty',
    'product_weight_g',
    'product_length_cm',
    'product_height_cm',
    'product_width_cm'
]

for col in missing_cols:
    products[col] = (
        products
        .groupby('product_category_name')[col]
        .transform(lambda x: x.fillna(x.median()))
    )
    products[col] = products[col].fillna(products[col].median())
print('\n\nAfter')
print(products.shape)
print(products.isna().sum())

Before
(32951, 9)
product_id                      0
product_category_name         623
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64


After
(32951, 9)
product_id                    0
product_category_name         0
product_name_lenght           0
product_description_lenght    0
product_photos_qty            0
product_weight_g              0
product_length_cm             0
product_height_cm             0
product_width_cm              0
dtype: int64

In [22]:
# sellers
print('Before')
print(sellers.isna().sum())
print('shape = ',sellers.shape)

sellers = sellers.merge(geo_location , how='left' , left_on='seller_zip_code_prefix' , right_on='geolocation_zip_code_prefix')
sellers['seller_city'] =sellers['seller_city'].fillna(sellers['geolocation_city'])
sellers['seller_state'] =sellers['seller_state'].fillna(sellers['geolocation_state'])
sellers = sellers.drop(columns=[
    'geolocation_zip_code_prefix',
    'geolocation_lat',
    'geolocation_lng',
    'geolocation_city', 
    'geolocation_state']
)
sellers.isna().sum()


print('\n\nAfter')
print(sellers.isna().sum())
print('shape = ',sellers.shape)

Before
seller_id                  0
seller_zip_code_prefix     0
seller_city               57
seller_state              57
dtype: int64
shape =  (3095, 4)


After
seller_id                 0
seller_zip_code_prefix    0
seller_city               0
seller_state              0
dtype: int64
shape =  (3095, 4)

In [23]:
# filtering the data 
cuttoff = orders['order_purchase_timestamp'].max() - pd.DateOffset(years=2)
orders = orders[
    orders['order_purchase_timestamp'] >= cuttoff
]

orders_itmes = orders_itmes[orders_itmes['order_id'].isin(orders['order_id'])]
orders_payments = orders_payments[orders_payments['order_id'].isin(orders['order_id'])]
order_review_ratings = order_review_ratings[order_review_ratings['order_id'].isin(orders['order_id'])]

In [24]:
orders['order_purchase_timestamp'].min()

Timestamp('2016-10-22 08:25:00')

# EDA